KREAM_ProyectoFinal/Controllers/VendedorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KREAM_ProyectoFinal.Models;
using PURIS_FLASH.Models;
using PURIS_FLASH.Models.TableViewModel;
using PURIS_FLASH.Models.ViewModel;

namespace PURIS_FLASH.Controllers
{
    // Atributo que verifica si hay una sesión activa antes de permitir el acceso al controlador.
    [VerificarSesion]
    public class VendedorController : Controller
    {
        // Acción GET para mostrar la lista de productos con la posibilidad de aplicar filtros.
        public ActionResult Index(string nombre, string personas, string lugar, string proveedor, decimal? precio, decimal? precioMin, decimal? precioMax, string categoria)
        {
            // Recupera el usuario actual desde la sesión y lo pasa a la vista mediante ViewBag.
            var usuarioActual = Session["UsuarioActual"] as UsersViewModel;
            ViewBag.UsuarioActual = usuarioActual.Nombre;
            ViewBag.SexoUsuario = usuarioActual.Sexo;
            ViewBag.TipoUsuario = usuarioActual.TipoDeUsuario;

            // Inicializa una lista de productos para la vista.
            List<ProductosTableViewModel> lstProductos = new List<ProductosTableViewModel>();

            // Usa la base de datos para consultar los productos.
            using (TRAVEL2Entities db = new TRAVEL2Entities())
            {
                var query = from p in db.Productos
                            select new ProductosTableViewModel
                            {
                                ProductoID = p.ProductoID,
                                Nombre = p.Nombre,
                                Lugar = p.Lugar,
                                Descripcion = p.Descripcion,
                                Precio = (decimal)p.Precio,
                                Categoria = p.Categoria,
                                Personas = p.Personas,
                                CantidadEnStock = p.CantidadEnStock,
                                Comentario = p.Comentarios,
                                Proveedor = p.Proveedor,
                                Imagen = p.Imagen,
                                Imagen2 = p.Imagen2,
                                Imagen3 = p.Imagen3,
                            };

                // Aplicar filtros según los parámetros recibidos.
                if (!string.IsNullOrEmpty(categoria))
                {
                    query = query.Where(p => p.Categoria.Contains(categoria));
                }

                if (!string.IsNullOrEmpty(lugar))
                {
                    query = query.Where(p => p.Lugar.Contains(lugar));
                }

                if (!string.IsNullOrEmpty(nombre))
                {
                    query = query.Where(p => p.Nombre.Contains(nombre));
                }

                // Convertir la consulta en una lista de productos.
                lstProductos = query.ToList();
            }

            // Devuelve la vista con la lista de productos filtrados.
            return View(lstProductos);
        }

        // --------------------------------------------  ADD  -----------------------------------------------

        // Acción GET que muestra la vista para agregar un nuevo producto.
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        // Acción POST que maneja la lógica para agregar un nuevo producto.
        [HttpPost]
        [ValidateInput(false)] // Permite la entrada de HTML, necesaria para manejar las imágenes.
        public ActionResult Add(ProductosTableViewModel model, HttpPostedFileBase ImagenFile, HttpPostedFileBase ImagenFile2, HttpPostedFileBase ImagenFile3)
        {
            // Verifica si el modelo es válido.
            if (!ModelState.IsValid) return View(model);

            // Usa la base de datos para agregar el nuevo producto.
            using (var db = new TRAVEL2Entities())
            {
                // Recupera el usuario actual desde la sesión.
                var usuario = Session["UsuarioActual"] as UsersViewModel;

                // Variables para almacenar las imágenes en bytes.
                byte[] imagenBytes = null;
                byte[] imagenBytes2 = null;
                byte[] imagenBytes3 = null;

                // Procesa la primera imagen.
                if (ImagenFile != null && ImagenFile.ContentLength > 0)
                {
                    using (var binaryReader = new BinaryReader(ImagenFile.InputStream))
                    {
                        imagenBytes = binaryReader.ReadBytes(ImagenFile.ContentLength);
                    }
                }

                // Procesa la segunda imagen.
                if (ImagenFile2 != null && ImagenFile2.ContentLength > 0)
                {
                    using (var binaryReader = new BinaryReader(ImagenFile2.InputStream))
                    {
                        imagenBytes2 = binaryReader.ReadBytes(ImagenFile2.ContentLength);
                    }
                }

                // Procesa la tercera imagen.
                if (ImagenFile3 != null && ImagenFile3.ContentLength > 0)
                {
                    using (var binaryReader = new BinaryReader(ImagenFile3.InputStream))
                    {
                        imagenBytes3 = binaryReader.ReadBytes(ImagenFile3.ContentLength);
                    }
                }

                // Crea una nueva instancia de la entidad Productos con los datos proporcionados.
                Productos productoTO = new Productos
                {
                    Nombre = model.Nombre,
                    Lugar = model.Lugar,
                    Descripcion = model.Descripcion,
                    Precio = model.Precio,
                    Categoria = model.Categoria,
                    Personas = model.Personas,
                    CantidadEnStock = model.CantidadEnStock,
                    Comentarios = model.Comentario,
                    Calificacion = model.Calificacion,
                    Proveedor = model.Proveedor,
                    Vendedor = usuario.Cedula, // Asigna la cédula del vendedor al producto.
                    Imagen = imagenBytes,
                    Imagen2 = imagenBytes2,
                    Imagen3 = imagenBytes3
                };

                // Agrega el producto a la base de datos y guarda los cambios.
                db.Productos.Add(productoTO);
                db.SaveChanges();

                // Redirige al usuario a la página de índice después de agregar el producto.
                return Redirect(Url.Content("~/Vendedor/Index"));
            }
        }

        // --------------------------------------------  EDIT  -----------------------------------------------

        // Acción GET que muestra la vista para editar un producto específico.
        [HttpGet]
        public ActionResult Edit(int ProductoID)
        {
            using (var db = new TRAVEL2Entities())
            {
                // Busca el producto por su ID.
                var producto = db.Productos.Find(ProductoID);

                // Guarda el nombre del producto en un ViewBag para usarlo en la vista de edición.
                ViewBag.ProductoNombre = producto.Nombre;
                ViewBag.ProductoGenero = producto.Lugar;

                // Si el producto no se encuentra, redirige al índice.
                if (producto == null)
                {
                    return RedirectToAction("Index");
                }

                // Mapea los datos del producto al modelo de la vista.
                var model = new ProductosTableViewModel
                {
                    Nombre = producto.Nombre,
                    Lugar = producto.Lugar,
                    Descripcion = producto.Descripcion,
                    Precio = (decimal)producto.Precio,
                    Categoria = producto.Categoria,
                    CantidadEnStock = producto.CantidadEnStock,
                    Comentario = producto.Comentarios,
                    Calificacion = producto.Calificacion != null ? (int)producto.Calificacion : 0,
                    Proveedor = producto.Proveedor
                };

                // Guarda el proveedor actual en un ViewBag para usarlo en la vista.
                ViewBag.GeneroSeleccionado = producto.Proveedor;

                // Devuelve la vista con el modelo de producto.
                return View(model);
            }
        }

        // Acción POST que maneja la lógica para actualizar un producto.
        [HttpPost]
        public ActionResult Edit(ProductosTableViewModel model, HttpPostedFileBase NuevaImagen, HttpPostedFileBase NuevaImagen2, HttpPostedFileBase NuevaImagen3, string action)
        {
            // Verifica si el modelo es válido.
            if (!ModelState.IsValid) return View(model);

            using (var db = new TRAVEL2Entities())
            {
                // Busca el producto por su ID en la base de datos.
                var productoTO = db.Productos.Find(model.ProductoID);

                // Actualiza las propiedades del producto con los valores del modelo.
                productoTO.Nombre = model.Nombre;
                productoTO.Lugar = model.Lugar;
                productoTO.Descripcion = model.Descripcion;
                productoTO.Precio = model.Precio;
                productoTO.Categoria = model.Categoria;
                productoTO.CantidadEnStock = model.CantidadEnStock;
                productoTO.Comentarios = model.Comentario;
                productoTO.Calificacion = model.Calificacion;
                productoTO.Proveedor = model.Proveedor;

                // Actualiza las imágenes del producto según las acciones del usuario.
                if (NuevaImagen != null && NuevaImagen.ContentLength > 0)
                {

KREAM_ProyectoFinal/Views/Vendedor/Add.cshtml
@model PURIS_FLASH.Models.TableViewModel.ProductosTableViewModel
@{
    ViewBag.Title = "Agregar Nuevo Tour";
}

<style>
    body {
        background-color: white;
        font-family: Arial, sans-serif;
    }

    h2 {
        text-align: center;
        margin-top: 20px;
    }

    .container-add {
        margin-top: 20px;
        padding: 20px;
        background-color: #f8f9fa;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.1);
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-label {
        font-weight: bold;
    }

    .form-control {
        border: 1px solid #ced4da;
        border-radius: 5px;
        padding: 10px;
    }

    input[type="submit"],
    input[type="button"] {
        width: auto;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

        input[type="submit"].btn-primary {
            background-color: #28a745;
            color: white;
        }

        input[type="button"].btn-outline-danger {
            background-color: transparent;
            border: 2px solid #dc3545;
            color: #dc3545;
        }

            input[type="button"].btn-outline-danger:hover {
                background-color: #dc3545;
                color: white;
            }
</style>

<h2>Agregar Nuevo Tour</h2>

<div class="container-add">


    @using (Html.BeginForm("Add", "Vendedor", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <!-- Campos del formulario para agregar un nuevo producto -->

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lugar, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Lugar, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Lugar, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label" })
            @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>

        <div class="col-md-6">
            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "form-label" })
            <select id="GeneroDropdown" name="Categoria" class="form-control" data-val="true" data-val-required="La selección es obligatoria.">
                <option value="" selected>-- Categoria --</option>
                <option value="Baja">Baja</option>
                <option value="Alta">Alta</option>
            </select>
            @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Personas, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Personas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Personas, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CantidadEnStock, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.CantidadEnStock, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CantidadEnStock, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Proveedor, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Proveedor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Proveedor, "", new { @class = "text-danger" })
        </div>



        // IMAGENES

        <!-- IMAGENES -->
        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, "Imagen")
            <input type="file" name="ImagenFile" id="ImagenFile" class="form-control" onchange="previewImage(this, 'previewImagen')" />
            <img id="previewImagen" style="max-width: 200px; max-height: 200px; margin-top: 10px;" />
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen2, "Imagen2")
            <input type="file" name="ImagenFile2" id="ImagenFile2" class="form-control" onchange="previewImage(this, 'previewImagen2')" />
            <img id="previewImagen2" style="max-width: 200px; max-height: 200px; margin-top: 10px;" />
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen3, "Imagen3")
            <input type="file" name="ImagenFile3" id="ImagenFile3" class="form-control" onchange="previewImage(this, 'previewImagen3')" />
            <img id="previewImagen3" style="max-width: 200px; max-height: 200px; margin-top: 10px;" />
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-primary" />
                <input type="button" class="btn btn-outline-danger" value="Regresar"
                       onclick="document.location.href = '@Url.Content("~/Vendedor/index")'" />
            </div>
        </div>
    }


</div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    function previewImage(input, previewId) {
        var preview = document.getElementById(previewId);
        var file = input.files[0];
        var reader = new FileReader();

        reader.onloadend = function () {
            preview.src = reader.result;
        };

        if (file) {
            reader.readAsDataURL(file);
        } else {
            preview.src = "";
        }
    }
</script>

KREAM_ProyectoFinal/Views/Vendedor/Edit.cshtml
@model PURIS_FLASH.Models.TableViewModel.ProductosTableViewModel

@{
    ViewBag.Title = "Editar Producto";
}

<h2 class="text-center mt-4 mb-5">Editando Productos: @ViewBag.TourNombre</h2>

<div class="container">
    @using (Html.BeginForm("Edit", "Vendedor", FormMethod.Post, new { enctype = "multipart/form-data", @class = "row g-3" }))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.ProductoID)

        <div class="col-md-6">
            <label class="form-label">Nombre del Producto:</label>
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>

        <div class="col-md-6">
            <label class="form-label">Lugar</label>
            @Html.EditorFor(model => model.Lugar, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Lugar, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label" })
            @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>



        <div class="col-md-6">
            <label class="form-label">CantidadEnStock</label>
            @Html.EditorFor(model => model.CantidadEnStock, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CantidadEnStock, "", new { @class = "text-danger" })
        </div> 


        <div class="col-md-6">
            <label class="form-label">Precio</label>
            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>

        <div class="col-md-6">
            <label class="form-label">Categoria</label>
            @Html.EditorFor(model => model.Categoria, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
        </div>

        

        <div class="col-md-6">
            <label class="form-label">Proveedor</label>
            @Html.EditorFor(model => model.Proveedor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Proveedor, "", new { @class = "text-danger" })
        </div>



        <div class="col-md-6 offset-6">
            <label class="form-label">Imagen 1</label>
            <input class="form-control" type="file" name="NuevaImagen" onchange="mostrarImagenCargada(this, 'Imagen', 'imagenActual', 'contenedorImagen')" />
            @if (Model.Imagen != null && Model.Imagen.Length > 0)
            {
                <div class="mt-3">
                    <img id="imagenActual" src="data:image;base64,@Convert.ToBase64String(Model.Imagen)" class="img-thumbnail" alt="Imagen actual 1" />
                </div>
            }
        </div>


        <div class="col-md-6 offset-6">
            <label class="form-label">Imagen 2</label>
            <input class="form-control" type="file" name="NuevaImagen2" onchange="mostrarImagenCargada(this, 'Imagen2', 'imagenActual2', 'contenedorImagen2')" />
            @if (Model.Imagen2 != null && Model.Imagen2.Length > 0)
            {
                <div class="mt-3">
                    <img id="imagenActual2" src="data:image;base64,@Convert.ToBase64String(Model.Imagen2)" class="img-thumbnail" alt="Imagen actual 2" />
                </div>
            }
        </div>

        <div class="col-md-6 offset-6">
            <label class="form-label">Imagen 3</label>
            <input class="form-control" type="file" name="NuevaImagen3" onchange="mostrarImagenCargada(this, 'Imagen3', 'imagenActual3', 'contenedorImagen3')" />
            @if (Model.Imagen3 != null && Model.Imagen3.Length > 0)
            {
                <div class="mt-3">
                    <img id="imagenActual3" src="data:image;base64,@Convert.ToBase64String(Model.Imagen3)" class="img-thumbnail" alt="Imagen actual 3" />
                </div>
            }
        </div>

        <div class="col-12 mt-4">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a class="btn btn-secondary ms-2" href="@Url.Content("~/Vendedor/Index")">Regresar</a>
        </div>
    }
</div>

<script>
    function mostrarImagenCargada(input, id, imagenId, contenedorId) {
        var imagen = document.getElementById(imagenId);
        imagen.onload = function () {
            imagen.style.display = "block";
        };
        imagen.src = URL.createObjectURL(input.files[0]);
    }
</script>

<style>
    .img-thumbnail {
        width: 100%;
        max-width: 200px;
        height: auto;
    }
</style>

KREAM_ProyectoFinal/Views/Vendedor/Perfil.cshtml
@model KREAM_ProyectoFinal.Models.Users

@{
    ViewBag.Title = "Perfil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Perfil</h2>

KREAM_ProyectoFinal/Views/Vendedor/_LayoutPerfil.cshtml
@using KREAM_ProyectoFinal.Models.ViewModel

@{
    ViewBag.Title = "Perfil";
    var usuario = Session["UsuarioActual"] as UsersViewModel;
}

<!DOCTYPE html>
<html>
<head>


    <title>@Page.Title</title>
    @RenderSection("head", required: false)

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link href="~/Content/bootstrap-utilities.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.20.0/jquery.validate.min.js"
            integrity="sha512-WMEKGZ7L5LWgaPeJtw9MBM4i5w5OSBlSjTjCtSnvFJGSVD26gE5+Td12qN5pvWXhuWaWcVwF++F7aqu9cvqP0A=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <style>



        .topbar {
            display: flex;
            flex-wrap: nowrap;
            align-items: stretch;
            justify-content: space-evenly;
            height: 5vh;
            margin-bottom: 25px;
        }

        .tabs {
            display: flex;
            flex-grow: 1;
            justify-content: center;
            align-items: stretch;
            justify-content: center;
        }

        .opciones {
            background: #ffffff;
            display: flex;
            align-items: center;
            justify-content: center;
            flex: 1;
            font-family: Staatliches;
            font-size: 15px;
            text-align: center;
            vertical-align: middle;
        }
    </style>


</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light" style="border-bottom: 2px solid #a9a7a2bc; padding-bottom: 0px; padding-top: 0px">
        <a class="navbar-brand" href="#" style="font-family: 'Stalinist One'; font-size: 28px; padding-left: 20px">
            K.R.E.A.M
        </a>
        <div class="container" style="font-family: Staatliches">

            @if (ViewBag.TipoUsuario == 1) // ADMIN
            {
                <!-- Imprimiendo el nombre de la persona según su nombre y sexo (bienvenido/bienvenida) registrado -->
                @Html.ActionLink("ENTRO EN EL IF ADMIN", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            }
            else if (ViewBag.TipoUsuario == 2) // VENDEDOR
            {
                @Html.ActionLink("ENTRO EN EL IF VENDEDOR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            }
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">

                    @if (ViewBag.TipoUsuario == 1) // ADMIN
                    {
                        <li>@Html.ActionLink("MENU ADMIN", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>


                    }
                    else if (ViewBag.TipoUsuario == 2) // VENDEDOR
                    {
                        <li>@Html.ActionLink("MENU VENDEDOR", "Index", "Vendedor", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                    }
                    else if (ViewBag.TipoUsuario == 3) // COMPRADOR
                    {

                        <li>@Html.ActionLink("MENU COMPRADOR", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    }


                </ul>



                <!--CODIGO PARA QUE LA PERSONA HAGA LOG OUT Y SUELTE EL USERSESSION  | esto solo pasa si la persona no es Null o si ya se logueo sino no sale-->
                <!-- PARA USAR ESTO PRIMERO TIENEN QUE ESTAR SEGUROS QUE EL HEADER DE ESTA PAGINA CONTIENE LOS CONTROLADORES NECESARIOS , YA LUEGO SI USAN USUARIO.[LO QUE QUIERAN]-->
                <div class="d-flex">
                    @if (usuario != null)
                    {
                        <span class="text-dark font-weight-bold my-auto mx-1">Bienvenido: @usuario.Nombre </span>
                        <span class="text-dark font-weight-bold my-auto mx-3">
                            <i class="bi bi-person-circle"></i>  @ViewBag.UserSession
                        </span>
                        <a href="@Url.Action("Logout","Login")" class="btn btn-outline-primary" title="Cerrar Sesión">
                            <i class="bi bi-box-arrow-right"></i>
                        </a>
                    }
                </div>


            </div>
        </div>
    </nav>

    <div class="topbar">
        <div class="tabs">
            <div class="opciones" style="border-left: 2px solid #a9a7a2bc">Perfil</div>
            <div class="opciones">Informacion de Pago</div>
            <div class="opciones">Productos</div>
            <div class="opciones" style="border-right: 2px solid #a9a7a2bc">Configuracion</div>
        </div>
    </div>

    <div class="container body-content">



    </div>
    @RenderBody()
    <hr />














    <footer style="margin: 0px;">
        <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
    </footer>

    @*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.20.0/jquery.validate.min.js"
            integrity="sha512-WMEKGZ7L5LWgaPeJtw9MBM4i5w5OSBlSjTjCtSnvFJGSVD26gE5+Td12qN5pvWXhuWaWcVwF++F7aqu9cvqP0A=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>*@






</body>


</html>