KREAM_ProyectoFinal/Models/Repartidores.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KREAM_ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repartidores
    {
        public int IDRepartidor { get; set; }
        public string TipoDeTransporte { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string NombreRepartidor { get; set; }
        public byte[] Imagen { get; set; }
        public byte[] Imagen2 { get; set; }
        public byte[] Imagen3 { get; set; }
    }
}

KREAM_ProyectoFinal/Controllers/RepartidoresController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KREAM_ProyectoFinal.Models.TableViewModel;
using KREAM_ProyectoFinal.Models;
using PURIS_FLASH.Models;
using PURIS_FLASH.Models.TableViewModel;
using PURIS_FLASH.Models.ViewModel;

namespace PURIS_FLASH.Controllers
{
    // Atributo que verifica si hay una sesión activa antes de permitir el acceso al controlador.
    [VerificarSesion]
    public class RepartidoresController : Controller
    {
        // Método que maneja la vista principal de repartidores, permitiendo la búsqueda y filtrado por nombre y tipo de transporte.
        public ActionResult Index(string nombre, string transporte)
        {
            // Recupera el usuario actual desde la sesión.
            var usuarioActual = Session["UsuarioActual"] as UsersViewModel;

            // Pasa la información del usuario a la vista mediante ViewBag.
            ViewBag.UsuarioActual = usuarioActual.Nombre;
            ViewBag.TipoUsuario = usuarioActual.TipoDeUsuario;

            // Inicializa una lista de repartidores.
            List<RepartidoresTableViewModel> lstRepartidores = new List<RepartidoresTableViewModel>();

            // Usa la base de datos para realizar consultas sobre los repartidores.
            using (TRAVEL2Entities db = new TRAVEL2Entities())
            {
                // Consulta básica para seleccionar repartidores de la base de datos y mapearlos a la vista.
                var query = from r in db.Repartidores
                            select new RepartidoresTableViewModel
                            {
                                IDRepartidor = r.IDRepartidor,
                                NombreRepartidor = r.NombreRepartidor,
                                TipoDeTransporte = r.TipoDeTransporte,
                                Descripcion = r.Descripcion,
                                Telefono = (int)r.Telefono,
                                Imagen = r.Imagen,
                                Imagen2 = r.Imagen2,
                                Imagen3 = r.Imagen3,
                            };

                // Filtrar por nombre del repartidor si se proporciona.
                if (!string.IsNullOrEmpty(nombre))
                {
                    query = query.Where(r => r.NombreRepartidor.Contains(nombre));
                }
                ViewBag.NombreRepartidorSeleccionado = nombre;

                // Filtrar por tipo de transporte si se proporciona.
                if (!string.IsNullOrEmpty(transporte))
                {
                    query = query.Where(r => r.TipoDeTransporte.Contains(transporte));
                }

                // Obtener la lista de tipos de transporte distintos de la base de datos.
                var transportes = db.Repartidores.Select(r => r.TipoDeTransporte).Distinct().ToList();
                ViewBag.Categoria = new SelectList(transportes);

                // Pasa el tipo de transporte seleccionado a la vista.
                ViewBag.TipoDeTransporteSeleccionado = transporte;

                // Convierte la consulta en una lista de repartidores.
                lstRepartidores = query.ToList();
            }

            // Devuelve la vista con la lista de repartidores filtrados.
            return View(lstRepartidores);
        }

        // ------------------------------------------- MENÚ PRINCIPAL DE ADMINISTRACIÓN DE REPARTIDORES --------------------------------

        // Método que maneja la visualización de la información de los repartidores, permitiendo al administrador eliminar, editar o crear nuevos repartidores.
        public ActionResult MostrarInformacion(string tipoDeTransporte, int? Telefono, string NombreRepartidor)
        {
            // Recupera el usuario actual desde la sesión.
            var usuarioActual = Session["UsuarioActual"] as UsersViewModel;

            // Pasa la información del usuario a la vista mediante ViewBag.
            ViewBag.UsuarioActual = usuarioActual.Nombre;
            ViewBag.SexoUsuario = usuarioActual.Sexo;
            ViewBag.TipoUsuario = usuarioActual.TipoDeUsuario;

            // Inicializa una lista de repartidores.
            List<RepartidoresTableViewModel> lstRepartidores = new List<RepartidoresTableViewModel>();

            // Usa la base de datos para realizar consultas sobre los repartidores.
            using (TRAVEL2Entities db = new TRAVEL2Entities())
            {
                // Consulta básica para seleccionar repartidores de la base de datos y mapearlos a la vista.
                var query = from r in db.Repartidores
                            select new RepartidoresTableViewModel
                            {
                                IDRepartidor = r.IDRepartidor,
                                NombreRepartidor = r.NombreRepartidor,
                                TipoDeTransporte = r.TipoDeTransporte,
                                Descripcion = r.Descripcion,
                                Telefono = (int)r.Telefono,
                                Imagen = r.Imagen,
                                Imagen2 = r.Imagen2,
                                Imagen3 = r.Imagen3,
                            };

                // Filtrar por nombre del repartidor si se proporciona.
                if (!string.IsNullOrEmpty(NombreRepartidor))
                {
                    query = query.Where(r => r.NombreRepartidor.Contains(NombreRepartidor));
                }

                // Obtener la lista de tipos de transporte distintos de la base de datos.
                var transportes = db.Repartidores.Select(r => r.TipoDeTransporte).Distinct().ToList();
                ViewBag.Categoria = new SelectList(transportes);

                // Pasa los parámetros seleccionados a la vista.
                ViewBag.TipoDeTransporteSeleccionado = tipoDeTransporte;
                ViewBag.NombreRepartidorSeleccionado = NombreRepartidor;

                // Convierte la consulta en una lista de repartidores.
                lstRepartidores = query.ToList();
            }

            // Devuelve la vista con la lista de repartidores filtrados.
            return View(lstRepartidores);
        }

        //---------------------------------------------- FUNCIONALIDAD DEL BOTÓN "ADD REPARTIDORES" -------------------------------- 

        // Método que muestra la vista para agregar un nuevo repartidor.
        [HttpGet]
        public ActionResult Add()
        {
            // Establecer el ViewBag.Categoria con tipos de transporte antes de cargar la vista.
            using (var db = new TRAVEL2Entities())
            {
                var transportes = db.Repartidores.Select(r => r.TipoDeTransporte).Distinct().ToList();
                ViewBag.Categoria = new SelectList(transportes);
            }

            return View();
        }

        // Método que maneja la lógica para agregar un nuevo repartidor.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(RepartidoresTableViewModel model, HttpPostedFileBase ImagenFile, HttpPostedFileBase ImagenFile2, HttpPostedFileBase ImagenFile3)
        {
            // Si el modelo no es válido, devuelve la vista con el modelo actual.
            if (!ModelState.IsValid)
            {
                // Reestablecer ViewBag.Categoria antes de devolver la vista.
                using (var db = new TRAVEL2Entities())
                {
                    var transportes = db.Repartidores.Select(r => r.TipoDeTransporte).Distinct().ToList();
                    ViewBag.Categoria = new SelectList(transportes);
                }

                return View(model);
            }

            // Usa la base de datos para agregar el nuevo repartidor.
            using (var db = new TRAVEL2Entities())
            {
                // Procesa la primera imagen.
                byte[] imagenBytes = null;
                if (ImagenFile != null && ImagenFile.ContentLength > 0)
                {
                    using (var binaryReader = new BinaryReader(ImagenFile.InputStream))
                    {
                        imagenBytes = binaryReader.ReadBytes(ImagenFile.ContentLength);
                    }
                }

                // Procesa la segunda imagen.
                byte[] imagenBytes2 = null;
                if (ImagenFile2 != null && ImagenFile2.ContentLength > 0)
                {
                    using (var binaryReader = new BinaryReader(ImagenFile2.InputStream))
                    {
                        imagenBytes2 = binaryReader.ReadBytes(ImagenFile2.ContentLength);
                    }
                }

                // Procesa la tercera imagen.
                byte[] imagenBytes3 = null;
                if (ImagenFile3 != null && ImagenFile3.ContentLength > 0)
                {
                    using (var binaryReader = new BinaryReader(ImagenFile3.InputStream))
                    {
                        imagenBytes3 = binaryReader.ReadBytes(ImagenFile3.ContentLength);
                    }
                }

                // Crea una nueva instancia de la entidad Repartidores con los datos proporcionados.
                var repartidorTO = new Repartidores
                {
                    NombreRepartidor = model.NombreRepartidor,
                    TipoDeTransporte = model.TipoDeTransporte,
                    Descripcion = model.Descripcion,
                    Telefono = model.Telefono,
                    Imagen = imagenBytes,
                    Imagen2 = imagenBytes2,
                    Imagen3 = imagenBytes3
                };

                // Agrega el repartidor a la base de datos y guarda los cambios.
                db.Repartidores.Add(repartidorTO);
                db.SaveChanges();

                // Redirige a la vista de mostrar información.

KREAM_ProyectoFinal/Views/Repartidores/Add.cshtml
@model KREAM_ProyectoFinal.Models.TableViewModel.RepartidoresTableViewModel
@{
    ViewBag.Title = "Agregar Nuevo Repartidor";
}

<style>
    body {
        background-color: white;
        font-family: Arial, sans-serif;
    }

    h2 {
        text-align: center;
        margin-top: 20px;
    }

    .container-add {
        margin-top: 20px;
        padding: 20px;
        background-color: #f8f9fa;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.1);
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-label {
        font-weight: bold;
    }

    .form-control {
        border: 1px solid #ced4da;
        border-radius: 5px;
        padding: 10px;
    }

    input[type="submit"],
    input[type="button"] {
        width: auto;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

        input[type="submit"].btn-primary {
            background-color: #28a745;
            color: white;
        }

        input[type="button"].btn-outline-danger {
            background-color: transparent;
            border: 2px solid #dc3545;
            color: #dc3545;
        }

            input[type="button"].btn-outline-danger:hover {
                background-color: #dc3545;
                color: white;
            }
</style>

<h2>Agregar Nuevo Repartidor</h2>

<div class="container-add">
    @using (Html.BeginForm("Add", "Repartidores", FormMethod.Post, new { enctype = "multipart/form-data", @class = "row g-3" }))
    {
        <!-- Campo para el nombre del repartidor -->
        <div class="col-md-6">
            @Html.LabelFor(model => model.NombreRepartidor, htmlAttributes: new { @class = "form-label" })
            @Html.EditorFor(model => model.NombreRepartidor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NombreRepartidor, "", new { @class = "text-danger" })
        </div>

        <!-- Campo para el tipo de transporte del repartidor -->
        <div class="col-md-6">
            @Html.LabelFor(model => model.TipoDeTransporte, htmlAttributes: new { @class = "form-label" })
            <select id="TransporteDropdown" name="TipoDeTransporte" class="form-control" data-val="true" data-val-required="La selección de transporte es obligatoria.">
                <option value="" selected>-- Tipo de Transporte --</option>
                <option value="Bicicleta">Bicicleta</option>
                <option value="Motocicleta">Motocicleta</option>
                <option value="Automóvil">Automóvil</option>
                <option value="Camion">Camion</option>
            </select>
            @Html.ValidationMessageFor(model => model.TipoDeTransporte, "", new { @class = "text-danger" })
        </div>

        <!-- Campo para la descripción del repartidor -->
        <div class="col-md-6">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "form-label" })
            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>

        <!-- Campos para las imágenes del repartidor -->
        <div class="col-md-6">
            @Html.LabelFor(model => model.Imagen, "Imagen")
            <input type="file" name="ImagenFile" id="ImagenFile" class="form-control" onchange="previewImage(this, 'previewImagen')" />
            <img id="previewImagen" style="max-width: 200px; max-height: 200px; margin-top: 10px;" />
        </div>

        <div class="col-md-6">
            @Html.LabelFor(model => model.Imagen2, "Imagen2")
            <input type="file" name="ImagenFile2" id="ImagenFile2" class="form-control" onchange="previewImage(this, 'previewImagen2')" />
            <img id="previewImagen2" style="max-width: 200px; max-height: 200px; margin-top: 10px;" />
        </div>

        <div class="col-md-6">
            @Html.LabelFor(model => model.Imagen3, "Imagen3")
            <input type="file" name="ImagenFile3" id="ImagenFile3" class="form-control" onchange="previewImage(this, 'previewImagen3')" />
            <img id="previewImagen3" style="max-width: 200px; max-height: 200px; margin-top: 10px;" />
        </div>

        <!-- Botones de acción -->
        <div class="col-12 mt-4">
            <input type="submit" value="Agregar" class="btn btn-primary" />
            <input type="button" class="btn btn-outline-danger ms-2" value="Regresar" onclick="document.location.href = '@Url.Content("~/Repartidores/MostrarInformacion")'" />
        </div>
    }
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    // Función para mostrar una vista previa de la imagen seleccionada
    function previewImage(input, previewId) {
        var preview = document.getElementById(previewId);
        var file = input.files[0];
        var reader = new FileReader();

        reader.onloadend = function () {
            preview.src = reader.result;
        };

        if (file) {
            reader.readAsDataURL(file);
        } else {
            preview.src = "";
        }
    }
</script>

KREAM_ProyectoFinal/Views/Repartidores/Edit.cshtml
@model KREAM_ProyectoFinal.Models.TableViewModel.RepartidoresTableViewModel

@{
    ViewBag.Title = "Editar Repartidor";
}

<h2 class="text-center mt-4 mb-5">Editando [ @ViewBag.RepartidorNombre ]</h2>
<div class="container">
    @* // Formulario para editar información del repartidor *@
    @using (Html.BeginForm("Edit", "Repartidores", FormMethod.Post, new { enctype = "multipart/form-data", @class = "row g-3" }))
    {
        @Html.AntiForgeryToken()

        @* // Campo oculto para el ID del repartidor *@
        @Html.HiddenFor(model => model.IDRepartidor)

        @* // Campo para editar el nombre del repartidor *@
        <div class="col-md-6">
            <label class="form-label">Nombre del Repartidor</label>
            @Html.EditorFor(model => model.NombreRepartidor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NombreRepartidor, "", new { @class = "text-danger" })
        </div>

        @* // Campo para seleccionar el tipo de transporte del repartidor *@
        <div class="col-md-6">
            <label class="form-label">Tipo de Transporte</label>
            @Html.DropDownListFor(model => model.TipoDeTransporte, new List<SelectListItem>
            {
                new SelectListItem { Value = "Moto", Text = "Moto" },
                new SelectListItem { Value = "Carro", Text = "Carro" },
                new SelectListItem { Value = "Bicicleta", Text = "Bicicleta" },
                new SelectListItem { Value = "Cuadraciclo", Text = "Cuadraciclo" },
                new SelectListItem { Value = "Camion", Text = "Camion" }
            }, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TipoDeTransporte, "", new { @class = "text-danger" })
        </div>

        @* // Campo para editar el teléfono del repartidor *@
        <div class="col-md-6">
            <label class="form-label">Teléfono (max 8 dígitos)</label>
            @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control", @type = "text", @pattern = "[0-9]{8}", @maxlength = "8", @inputmode = "numeric", @title = "Solo se permiten números con una longitud de 8 dígitos" })
            @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
        </div>

        @* // Campo para editar la descripción del repartidor *@
        <div class="col-md-6">
            <label class="form-label">Descripción</label>
            @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @rows = 5 })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>

        @* // Campo para subir la primera imagen del repartidor *@
        <div class="col-md-6">
            <label class="form-label">Imagen 1</label>
            <input class="form-control" type="file" name="NuevaImagen" onchange="mostrarImagenCargada(this, 'Imagen', 'imagenActual', 'contenedorImagen')" />
            @if (Model.Imagen != null && Model.Imagen.Length > 0)
            {
                <div class="mt-3">
                    <img id="imagenActual" src="data:image;base64,@Convert.ToBase64String(Model.Imagen)" class="img-thumbnail" alt="Imagen actual 1" />
                </div>
            }
        </div>

        @* // Campo para subir la segunda imagen del repartidor *@
        <div class="col-md-6 offset-6">
            <label class="form-label">Imagen 2</label>
            <input class="form-control" type="file" name="NuevaImagen2" onchange="mostrarImagenCargada(this, 'Imagen2', 'imagenActual2', 'contenedorImagen2')" />
            @if (Model.Imagen2 != null && Model.Imagen2.Length > 0)
            {
                <div class="mt-3">
                    <img id="imagenActual2" src="data:image;base64,@Convert.ToBase64String(Model.Imagen2)" class="img-thumbnail" alt="Imagen actual 2" />
                </div>
            }
        </div>

        @* // Campo para subir la tercera imagen del repartidor *@
        <div class="col-md-6 offset-6">
            <label class="form-label">Imagen 3</label>
            <input class="form-control" type="file" name="NuevaImagen3" onchange="mostrarImagenCargada(this, 'Imagen3', 'imagenActual3', 'contenedorImagen3')" />
            @if (Model.Imagen3 != null && Model.Imagen3.Length > 0)
            {
                <div class="mt-3">
                    <img id="imagenActual3" src="data:image;base64,@Convert.ToBase64String(Model.Imagen3)" class="img-thumbnail" alt="Imagen actual 3" />
                </div>
            }
        </div>

        @* // Botones para guardar los cambios o regresar *@
        <div class="col-12 mt-4">
            <button type="submit" class="btn btn-success">Guardar</button>
            <a class="btn btn-secondary ms-2" href="@Url.Content("~/Repartidores/MostrarInformacion")">Regresar</a>
        </div>
    }
</div>


<script>
    function mostrarImagenCargada(input, id, imagenId, contenedorId) {
        var imagen = document.getElementById(imagenId);
        imagen.onload = function () {
            imagen.style.display = "block";
        };
        imagen.src = URL.createObjectURL(input.files[0]);
    }
</script>

<style>
    .img-thumbnail {
        width: 100%;
        max-width: 200px;
        height: auto;
    }
</style>